/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e11c4a30-948b-42b4-8a7f-326b9dc757a3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_izs10QlPW",
    "aws_user_pools_web_client_id": "2i1rr1opj3l55ns6d8at0ck56j",
    "oauth": {}
};


export default awsmobile;
